name: App Builder
run-name: ${{ github.actor }} is building an app
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Install yarn 
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: yarn test

  build:
    needs: verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.8.0
    - name: Install yarn
      run: npm install -g yarn
    - name: Install dependencies
      run: yarn
    - name: Generate artifacts
      run: cd android && ./gradlew assembleRelease
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{github.ref_name}}-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
  test:
    needs: build
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      matrix:
        # test on minimum supported and last three version
        android: [21, 29, 30]
      fail-fast: false
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: Install app
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: 29
          target: google_apis
          emulator-options: >-
            -no-boot-anim -no-audio -no-snapshot -no-window -camera-back none
            -camera-front none -gpu swiftshader_indirect
          script: adb install ${{github.ref_name}}-release.apk
      - name: Setup maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash
      - name: Set path
        run: export PATH="$PATH":"$HOME/.maestro/bin"
      - name: Run test
        run: maestro test android-e2e.yaml   
        

